# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEquipamentos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_equipamentos(self):
    self.driver.get("https://dashboard.plataformabyou.com.br/visao-geral")
    self.driver.set_window_size(1382, 784)
    self.driver.execute_script("window.scrollTo(0,943)")
    self.driver.find_element(By.CSS_SELECTOR, ".fa-screwdriver-wrench > path").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiSvgIcon-colorAction")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiSvgIcon-colorAction").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) #more-info-button > .MuiSvgIcon-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) #more-info-button > .MuiSvgIcon-root").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-n85xso")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-n85xso").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) #more-info-button path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-n85xso")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".css-n85xso").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBadge-root > .css-1okqa6k > path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBadge-root > .css-1okqa6k > path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiAvatar-img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    element = self.driver.find_element(By.ID, "search-input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
