# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestClientes():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_clientes(self):
    # Test name: clientes
    # Step # | name | target | value
    # 1 | open | https://dashboard.plataformabyou.com.br/visao-geral | 
    self.driver.get("https://dashboard.plataformabyou.com.br/visao-geral")
    # 2 | setWindowSize | 1366x768 | 
    self.driver.set_window_size(1366, 768)
    # 3 | mouseOver | id=equipments-button | 
    element = self.driver.find_element(By.ID, "equipments-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | runScript | window.scrollTo(0,133) | 
    self.driver.execute_script("window.scrollTo(0,133)")
    # 5 | mouseOver | id=users-button | 
    element = self.driver.find_element(By.ID, "users-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | id=users-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | css=.fa-users > path | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-users > path").click()
    # 8 | click | css=.css-lnhqi5 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-lnhqi5").click()
    # 9 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 10 | type | id=search-input | rh
    self.driver.find_element(By.ID, "search-input").send_keys("rh")
    # 11 | click | css=.MuiChip-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiChip-label").click()
    # 12 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 13 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 14 | doubleClick | id=search-input | 
    element = self.driver.find_element(By.ID, "search-input")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 15 | mouseOver | id=resend-email-button | 
    element = self.driver.find_element(By.ID, "resend-email-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 16 | mouseOut | id=resend-email-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 17 | click | id=add-button | 
    self.driver.find_element(By.ID, "add-button").click()
    # 18 | click | id=name-edit-textfield-0 | 
    self.driver.find_element(By.ID, "name-edit-textfield-0").click()
    # 19 | click | id=name-edit-textfield-0 | 
    self.driver.find_element(By.ID, "name-edit-textfield-0").click()
    # 20 | doubleClick | id=name-edit-textfield-0 | 
    element = self.driver.find_element(By.ID, "name-edit-textfield-0")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 21 | click | id=name-edit-textfield-0 | 
    self.driver.find_element(By.ID, "name-edit-textfield-0").click()
    # 22 | type | id=name-edit-textfield-0 | teste
    self.driver.find_element(By.ID, "name-edit-textfield-0").send_keys("teste")
    # 23 | click | id=email-edit-textfield-1 | 
    self.driver.find_element(By.ID, "email-edit-textfield-1").click()
    # 24 | type | id=email-edit-textfield-1 | teste@gmail.com
    self.driver.find_element(By.ID, "email-edit-textfield-1").send_keys("teste@gmail.com")
    # 25 | type | id=phoneNumber-edit-textfield-2 | (17) 99757-1841
    self.driver.find_element(By.ID, "phoneNumber-edit-textfield-2").send_keys("(17) 99757-1841")
    # 26 | click | id=birthDate-edit-textfield-4 | 
    self.driver.find_element(By.ID, "birthDate-edit-textfield-4").click()
    # 27 | type | id=birthDate-edit-textfield-4 | 20/05/2001
    self.driver.find_element(By.ID, "birthDate-edit-textfield-4").send_keys("20/05/2001")
    # 28 | mouseDown | id=mui-component-select-sex | 
    element = self.driver.find_element(By.ID, "mui-component-select-sex")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 29 | mouseUp | css=.MuiBackdrop-invisible | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-invisible")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 30 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 31 | click | css=.MuiMenuItem-root:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(2)").click()
    # 32 | click | id=registry-edit-textfield-3 | 
    self.driver.find_element(By.ID, "registry-edit-textfield-3").click()
    # 33 | click | id=registry-edit-textfield-3 | 
    self.driver.find_element(By.ID, "registry-edit-textfield-3").click()
    # 34 | doubleClick | id=registry-edit-textfield-3 | 
    element = self.driver.find_element(By.ID, "registry-edit-textfield-3")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 35 | type | id=registry-edit-textfield-3 | 358.807.065-04
    self.driver.find_element(By.ID, "registry-edit-textfield-3").send_keys("358.807.065-04")
    # 36 | click | css=.css-1fgjyla | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1fgjyla").click()
    # 37 | click | id=height-edit-textfield-6 | 
    self.driver.find_element(By.ID, "height-edit-textfield-6").click()
    # 38 | click | id=registry-edit-textfield-3 | 
    self.driver.find_element(By.ID, "registry-edit-textfield-3").click()
    # 39 | click | id=registry-edit-textfield-3 | 
    self.driver.find_element(By.ID, "registry-edit-textfield-3").click()
    # 40 | doubleClick | id=registry-edit-textfield-3 | 
    element = self.driver.find_element(By.ID, "registry-edit-textfield-3")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 41 | click | id=registry-edit-textfield-3 | 
    self.driver.find_element(By.ID, "registry-edit-textfield-3").click()
    # 42 | type | id=registry-edit-textfield-3 | 886.957.890-98
    self.driver.find_element(By.ID, "registry-edit-textfield-3").send_keys("886.957.890-98")
    # 43 | click | id=add-user-button | 
    self.driver.find_element(By.ID, "add-user-button").click()
    # 44 | click | css=.css-1nujrx4:nth-child(1) > .MuiTableCell-root:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1nujrx4:nth-child(1) > .MuiTableCell-root:nth-child(1)").click()
    # 45 | click | css=.MuiTableRow-root:nth-child(1) .MuiChip-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .MuiChip-label").click()
    # 46 | click | css=.MuiTableRow-root:nth-child(1) .MuiChip-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .MuiChip-label").click()
    # 47 | click | css=.MuiTableRow-root:nth-child(1) .MuiChip-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .MuiChip-label").click()
    # 48 | doubleClick | css=.MuiTableRow-root:nth-child(1) .MuiChip-label | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) .MuiChip-label")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 49 | mouseOver | css=#resend-email-button > .MuiSvgIcon-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#resend-email-button > .MuiSvgIcon-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 50 | click | css=#resend-email-button > .MuiSvgIcon-root | 
    self.driver.find_element(By.CSS_SELECTOR, "#resend-email-button > .MuiSvgIcon-root").click()
    # 51 | mouseOut | css=#resend-email-button > .MuiSvgIcon-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 52 | click | id=email-text-field | 
    self.driver.find_element(By.ID, "email-text-field").click()
    # 53 | click | id=email-text-field | 
    self.driver.find_element(By.ID, "email-text-field").click()
    # 54 | doubleClick | id=email-text-field | 
    element = self.driver.find_element(By.ID, "email-text-field")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 55 | click | id=email-text-field | 
    self.driver.find_element(By.ID, "email-text-field").click()
    # 56 | type | id=email-text-field | teste@gmail.com
    self.driver.find_element(By.ID, "email-text-field").send_keys("teste@gmail.com")
    # 57 | sendKeys | id=email-text-field | ${KEY_ENTER}
    self.driver.find_element(By.ID, "email-text-field").send_keys(Keys.ENTER)
  
