# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProcedimentos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_procedimentos(self):
    # Test name: Procedimentos
    # Step # | name | target | value
    # 1 | open | https://dashboard.plataformabyou.com.br/visao-geral | 
    self.driver.get("https://dashboard.plataformabyou.com.br/visao-geral")
    # 2 | setWindowSize | 1382x784 | 
    self.driver.set_window_size(1382, 784)
    # 3 | runScript | window.scrollTo(0,943) | 
    self.driver.execute_script("window.scrollTo(0,943)")
    # 4 | mouseOver | id=procedures-button | 
    element = self.driver.find_element(By.ID, "procedures-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | click | id=procedures-button | 
    self.driver.find_element(By.ID, "procedures-button").click()
    # 6 | mouseOut | id=procedures-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 8 | mouseOver | css=.MuiTableRow-root:nth-child(1) #more-info-button path | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) #more-info-button path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | click | css=.MuiTableRow-root:nth-child(1) #more-info-button path | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) #more-info-button path").click()
    # 10 | mouseOut | css=.MuiTableRow-root:nth-child(1) #more-info-button path | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | mouseOver | css=.css-n85xso | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-n85xso")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | click | css=.css-n85xso | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-n85xso").click()
    # 13 | mouseOut | css=.css-n85xso | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 14 | mouseOver | css=.MuiTableRow-root:nth-child(2) #edit-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) #edit-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | click | css=.MuiTableRow-root:nth-child(2) #edit-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) #edit-button").click()
    # 16 | mouseOut | css=.MuiTableRow-root:nth-child(2) #edit-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 17 | click | id=name-textfield-0 | 
    self.driver.find_element(By.ID, "name-textfield-0").click()
    # 18 | click | id=name-textfield-0 | 
    self.driver.find_element(By.ID, "name-textfield-0").click()
    # 19 | doubleClick | id=name-textfield-0 | 
    element = self.driver.find_element(By.ID, "name-textfield-0")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 20 | type | id=name-textfield-0 | Procedimento teste 1
    self.driver.find_element(By.ID, "name-textfield-0").send_keys("Procedimento teste 1")
    # 21 | click | css=.MuiGrid-root:nth-child(2) > .MuiBox-root > .MuiBox-root > .MuiTypography-root:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(2) > .MuiBox-root > .MuiBox-root > .MuiTypography-root:nth-child(2)").click()
    # 22 | click | css=.MuiGrid-grid-xs-12:nth-child(2) > .MuiBox-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-grid-xs-12:nth-child(2) > .MuiBox-root").click()
    # 23 | click | css=.MuiGrid-root:nth-child(2) > .MuiBox-root > .MuiButtonBase-root > .MuiSvgIcon-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(2) > .MuiBox-root > .MuiButtonBase-root > .MuiSvgIcon-root").click()
    # 24 | click | id=confirm-button | 
    self.driver.find_element(By.ID, "confirm-button").click()
    # 25 | click | css=.css-isbt42 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-isbt42").click()
    # 26 | click | css=.css-isbt42 | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-isbt42").click()
    # 27 | click | id=equips-auto-complete | 
    self.driver.find_element(By.ID, "equips-auto-complete").click()
    # 28 | click | id=equips-auto-complete-option-1 | 
    self.driver.find_element(By.ID, "equips-auto-complete-option-1").click()
    # 29 | click | id=description-textfield-1 | 
    self.driver.find_element(By.ID, "description-textfield-1").click()
    # 30 | type | id=description-textfield-1 | Descrição do procedimento oi
    self.driver.find_element(By.ID, "description-textfield-1").send_keys("Descrição do procedimento oi")
    # 31 | sendKeys | id=description-textfield-1 | ${KEY_ENTER}
    self.driver.find_element(By.ID, "description-textfield-1").send_keys(Keys.ENTER)
    # 32 | click | css=.MuiDialog-container | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiDialog-container").click()
    # 33 | click | css=.css-10igwnb | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-10igwnb").click()
    # 34 | mouseOver | css=.css-w2aeda | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-w2aeda")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | click | css=.css-w2aeda | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-w2aeda").click()
    # 36 | mouseOut | css=.css-w2aeda | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 37 | mouseOver | css=.css-1w2t4ga | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1w2t4ga")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 38 | click | css=.css-1w2t4ga | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1w2t4ga").click()
    # 39 | mouseOver | css=.MuiTableRow-root:nth-child(3) #edit-button path | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) #edit-button path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 40 | click | css=.MuiTableRow-root:nth-child(3) #edit-button path | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) #edit-button path").click()
    # 41 | mouseOut | css=.MuiTableRow-root:nth-child(3) #edit-button path | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 42 | click | css=.MuiGrid-root:nth-child(1) > .MuiBox-root > .MuiBox-root .MuiBox-root:nth-child(1) > .MuiTypography-root:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(1) > .MuiBox-root > .MuiBox-root .MuiBox-root:nth-child(1) > .MuiTypography-root:nth-child(1)").click()
    # 43 | mouseOver | css=.css-w2aeda | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-w2aeda")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 44 | click | css=.css-w2aeda | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-w2aeda").click()
    # 45 | mouseOut | css=.css-w2aeda | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 46 | click | css=.css-10igwnb | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-10igwnb").click()
    # 47 | mouseOver | css=.css-w2aeda | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-w2aeda")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 48 | click | css=.css-w2aeda | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-w2aeda").click()
    # 49 | mouseOut | css=.css-w2aeda | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 50 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 51 | click | id=equips-auto-complete | 
    self.driver.find_element(By.ID, "equips-auto-complete").click()
    # 52 | click | id=equips-auto-complete-option-2 | 
    self.driver.find_element(By.ID, "equips-auto-complete-option-2").click()
    # 53 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 54 | click | id=submit-button | 
    self.driver.find_element(By.ID, "submit-button").click()
    # 55 | mouseDownAt | css=.MuiAlert-message | 213.953125,25
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 56 | mouseMoveAt | css=.MuiAlert-message | 213.953125,25
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 57 | mouseUpAt | css=.MuiAlert-message | 213.953125,25
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 58 | click | css=.MuiAlert-message | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message").click()
    # 59 | mouseDownAt | css=.MuiAlert-message | 43.953125,24
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 60 | mouseMoveAt | css=.MuiAlert-message | 43.953125,24
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 61 | mouseUpAt | css=.MuiAlert-message | 43.953125,24
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 62 | click | css=.MuiAlert-message | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiAlert-message").click()
    # 63 | mouseOver | css=.MuiIconButton-sizeSmall > .MuiSvgIcon-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiIconButton-sizeSmall > .MuiSvgIcon-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 64 | click | css=.MuiIconButton-sizeSmall > .MuiSvgIcon-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiIconButton-sizeSmall > .MuiSvgIcon-root").click()
    # 65 | mouseOut | css=.MuiIconButton-sizeSmall > .MuiSvgIcon-root | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 66 | mouseOver | css=.css-1w2t4ga | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1w2t4ga")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 67 | click | css=.css-1w2t4ga | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1w2t4ga").click()
    # 68 | mouseOut | css=.css-1w2t4ga | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 69 | click | css=.MuiDialog-paperWidthMd > .MuiDialogContent-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiDialog-paperWidthMd > .MuiDialogContent-root").click()
    # 70 | mouseOver | id=confirm-button | 
    element = self.driver.find_element(By.ID, "confirm-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 71 | click | id=confirm-button | 
    self.driver.find_element(By.ID, "confirm-button").click()
    # 72 | click | css=.css-1n9khni | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1n9khni").click()
    # 73 | click | css=.MuiMenuItem-root:nth-child(1) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(1) .MuiTypography-root").click()
    # 74 | click | css=.MuiButtonBase-root:nth-child(3) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) .MuiTypography-root").click()
    # 75 | click | css=.MuiButtonBase-root:nth-child(4) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) .MuiTypography-root").click()
    # 76 | click | css=.MuiBackdrop-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    # 77 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 78 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 79 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 80 | click | id=search-input | 
    self.driver.find_element(By.ID, "search-input").click()
    # 81 | mouseOver | css=.css-1n9khni | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1n9khni")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 82 | click | css=.css-1n9khni | 
    self.driver.find_element(By.CSS_SELECTOR, ".css-1n9khni").click()
    # 83 | mouseOut | css=.css-1n9khni | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 84 | click | css=.MuiMenuItem-root:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiMenuItem-root:nth-child(1)").click()
    # 85 | click | css=.MuiButtonBase-root:nth-child(3) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) .MuiTypography-root").click()
    # 86 | click | css=.MuiButtonBase-root:nth-child(4) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) .MuiTypography-root").click()
    # 87 | click | css=.MuiBackdrop-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    # 88 | mouseUp | id=search-input | 
    element = self.driver.find_element(By.ID, "search-input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
