# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegioesdeMedida():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_regioesdeMedida(self):
    # Test name: Regioes_de_Medida
    # Step # | name | target | value
    # 1 | open | https://dashboard.plataformabyou.com.br/visao-geral | 
    self.driver.get("https://dashboard.plataformabyou.com.br/visao-geral")
    # 2 | setWindowSize | 1382x784 | 
    self.driver.set_window_size(1382, 784)
    # 3 | runScript | window.scrollTo(0,943) | 
    self.driver.execute_script("window.scrollTo(0,943)")
    # 4 | click | css=.fa-ruler > path | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-ruler > path").click()
    # 5 | mouseOver | id=regions-button | 
    element = self.driver.find_element(By.ID, "regions-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOver | id=filter-button | 
    element = self.driver.find_element(By.ID, "filter-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | click | id=filter-button | 
    self.driver.find_element(By.ID, "filter-button").click()
    # 8 | mouseOut | id=filter-button | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | css=.MuiButtonBase-root:nth-child(2) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) .MuiTypography-root").click()
    # 10 | click | css=.MuiButtonBase-root:nth-child(3) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) .MuiTypography-root").click()
    # 11 | click | css=.MuiButtonBase-root:nth-child(4) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) .MuiTypography-root").click()
    # 12 | click | css=.MuiButtonBase-root:nth-child(5) .MuiTypography-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) .MuiTypography-root").click()
    # 13 | click | css=.MuiBackdrop-root | 
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    # 14 | mouseUp | id=search-input | 
    element = self.driver.find_element(By.ID, "search-input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
